### ISSUE TITLE
Add Redux Reducers

### ISSUE THREAD

**Issue by dincozdemir** [devinim-istanbul/shopping-list#17]
These are the initial reducers i thought of. We can add/remove/improve them.
```
sessionReducer
  state: { user: {}, house: {} }
  
listReducer
  state: { shoppingList: {} }
```

**Comment by dincozdemir** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Redux Reducers](https://trello.com/c/sFKZq05d/20-add-redux-reducers)

**Comment by yavrib** [comment]
As we have house reducers missing in the application, I am closing this issue. The new one can be found here #54
