### ISSUE TITLE
Application Entities

### ISSUE THREAD

**Issue by yavrib** [devinim-istanbul/shopping-list#2]
Establish application entities which will be used within the application.

**Comment by dincozdemir** [comment]
As it is, our initial **firebase** entities are as follows:

```
homes
- id
- name
- users
- shopping list
- items
user
- id
- homes.id
shopping-list
- id
- items
```

**Comment by erolkaftanoglu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Application Entities](https://trello.com/c/5Sdxig38/15-application-entities)

**Comment by yavrib** [comment]
Since @dincozdemir provided entities, we can close this issue.
