### ISSUE TITLE
Application Functions

### ISSUE THREAD

**Issue by yavrib** [devinim-istanbul/shopping-list#4]
Add basic folder structure for functions which will be established [here](https://github.com/devinim-istanbul/shopping-list/issues/1), that will be used by the application

**Comment by erolkaftanoglu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Application Functions](https://trello.com/c/zmffLvcn/13-application-functions)

**Comment by dincozdemir** [comment]
We will open new issues for more detailed use cases
